# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mingyuefly/MYYSpecs.git'
platform :ios, '13.0'

target 'activityOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~>4.0.1'
  pod 'MYYKit'
  pod 'SDWebImage'
  #pod 'YYKit'

end
